services:
  ##
  ## Start services required for OpenFlower (MongoDB and Redis)
  ##
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: openflower
      MONGO_INITDB_ROOT_USERNAME: openflower
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ./openflower-stacks/data/mongodb:/data/db
    restart: unless-stopped
    healthcheck: # https://github.com/rodrigobdz/docker-compose-healthchecks?tab=readme-ov-file#mongo
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      # test:
      #   [
      #     "CMD",
      #     "mongosh",
      #     "--quiet",
      #     "127.0.0.1/test",
      #     "--eval",
      #     "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
      #   ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    healthcheck: # https://stackoverflow.com/a/71504657
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 10

  ##
  ## Start OpenFlower backend services (api-service and node-service)
  ##
  openflower-api-service:
    image: flowerappengorg/openflower-api-service:latest
    container_name: openflower-api-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    environment:
      LOWCODER_PUBLIC_URL: "http://localhost:3000/"
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_MONGODB_URL: "mongodb://openflower:secret123@mongodb/openflower?authSource=admin"
      LOWCODER_REDIS_URL: "redis://redis:6379"
      LOWCODER_NODE_SERVICE_URL: "http://openflower-node-service:6060"
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_EMAIL_AUTH_ENABLED: "true"
      LOWCODER_EMAIL_SIGNUP_ENABLED: "true"
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: "true"
      #
      # ! PLEASE CHANGE THESE TO SOMETHING UNIQUE !
      #
      #    LOWCODER_DB_ENCRYPTION_PASSWORD and LOWCODER_DB_ENCRYPTION_SALT is used
      #    to encrypt sensitive data in database so it is important to change the defaults
      #
      LOWCODER_DB_ENCRYPTION_PASSWORD: "openflower.org"
      LOWCODER_DB_ENCRYPTION_SALT: "openflower.org"
      LOWCODER_CORS_DOMAINS: "*"
      LOWCODER_MAX_ORGS_PER_USER: 100
      LOWCODER_MAX_MEMBERS_PER_ORG: 1000
      LOWCODER_MAX_GROUPS_PER_ORG: 100
      LOWCODER_MAX_APPS_PER_ORG: 1000
      LOWCODER_MAX_DEVELOPERS: 50
      #
      # API-KEY secret - should be a string of at least 32 random characters
      #    - on linux/mac, generate one eg. with: head /dev/urandom | head -c 30 | shasum -a 256
      #
      LOWCODER_API_KEY_SECRET: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
      LOWCODER_PLUGINS_DIR: "../plugins"
      LOWCODER_API_RATE_LIMIT: 50
      LOWCODER_WORKSPACE_MODE: SAAS
      LOWCODER_MARKETPLACE_PRIVATE_MODE: "true"
      # Lowcoder notification emails setup
      LOWCODER_ADMIN_SMTP_HOST: smtp.gmail.com
      LOWCODER_ADMIN_SMTP_PORT: 587
      LOWCODER_ADMIN_SMTP_USERNAME:
      LOWCODER_ADMIN_SMTP_PASSWORD:
      LOWCODER_ADMIN_SMTP_AUTH: "true"
      LOWCODER_ADMIN_SMTP_SSL_ENABLED: "false"
      LOWCODER_ADMIN_SMTP_STARTTLS_ENABLED: "true"
      LOWCODER_ADMIN_SMTP_STARTTLS_REQUIRED: "true"
      # Email used as sender in lost password email
      LOWCODER_EMAIL_NOTIFICATIONS_SENDER: info@localhost
      # Lowcoder superuser details
      LOWCODER_SUPERUSER_USERNAME: admin@localhost
      # If left blank, a password will be generated and written into api-service log
      LOWCODER_SUPERUSER_PASSWORD:
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      #restart: true
      redis:
        condition: service_healthy
        #restart: true
    volumes:
      - ./openflower-stacks:/lowcoder-stacks
      - ./openflower-stacks/assets:/lowcoder/assets
      # - ./lowcoder-stacks:/lowcoder-stacks
      # - ./lowcoder-stacks/assets:/lowcoder/assets
    healthcheck: #https://stackoverflow.com/questions/71101967/how-should-i-use-grep-in-docker-compose-healthcheck
      test: curl -sS http://openflower-api-service:8080  | grep -c "API is up and runnig" > /dev/null
      interval: 3s
      timeout: 5s
      retries: 10

  openflower-node-service:
    image: flowerappengorg/openflower-node-service:latest
    container_name: openflower-node-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_API_SERVICE_URL: "http://openflower-api-service:8080"
    restart: unless-stopped
    depends_on:
      openflower-api-service:
        condition: service_healthy
        #restart: true
    healthcheck: #https://stackoverflow.com/questions/71101967/how-should-i-use-grep-in-docker-compose-healthcheck
      test: curl -sS http://openflower-node-service:6060  | grep -c "Node Service is up and running" > /dev/null
      interval: 3s
      timeout: 5s
      retries: 10

  ##
  ## Start OpenFlower web frontend
  ##
  openflower-frontend:
    image: flowerappengorg/openflower-frontend:latest
    container_name: openflower-frontend
    ports:
      - "3000:3000"
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_API_SERVICE_URL: "http://openflower-api-service:8080"
      LOWCODER_NODE_SERVICE_URL: "http://openflower-node-service:6060"
    restart: unless-stopped
    # Uncomment to serve local files as static assets
    # volumes:
    #   - ./static-assets:/openflower/assets

    depends_on:
      openflower-node-service:
        condition: service_healthy
        #restart: true
      openflower-api-service:
        condition: service_healthy
        #restart: true
    volumes:
      - ./openflower-stacks/assets:/lowcoder/assets
    healthcheck:
      test: curl --fail http://openflower-frontend:3000 || exit 1
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s
