name: Playwright OpenFlower Smoke Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "*/59 * * * *"    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd uiautomation/smoke_tests && npm ci
    - name: Install Playwright Browsers
      run: cd uiautomation/smoke_tests && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd uiautomation/smoke_tests && npx playwright test 
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30